name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    environment: Scratch_Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: |
          docker build -t figureofstick/team4_weather_api:latest .
      
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Push Docker image to registry
        run: |
          docker push figureofstick/team4_weather_api:latest
  
  deploy:
    needs: build
    environment: development-scratch
    runs-on: ubuntu-latest
    steps:
      - name: SSH into AWS EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_IP_ADDRESS }}
          username: ${{ secrets.AWS_EC2_USER_NAME }}
          password: ${{ secrets.AWS_EC2_DOCKER_SERVICE_PASSWORD }}
          script: |
            # Dummy code
            whoami
            # Pull Docker image from registry
            docker pull figureofstick/team4_weather_api:latest
            
            # Run Docker container
            docker run -d -p 80:80 figureofstick/team4_weather_api:latest
            docker ps
